export * as Process1 from './1.png'
export * as Process2 from './2.jpg'
export * as Process3 from './3.png'
export * as Process4 from './4.png'
export * as Process5 from './5.png'
export * as Process6 from './6.png'
export * as Process7 from './7.jpg'
export * as Process8 from './8.png'
export * as Process9 from './9.jpg'
export * as Process10 from './10.png'
export * as Process10b from './10B.png'

