export * as Background1 from './1.png'
export * as Background2 from './2.png'
export * as Background3 from './3.png'
export * as Background4 from './4.jpg'
export * as Background5 from './5.jpg'
export * as Background6 from './6.png'
export * as Background7 from './7.png'
export * as Background8 from './8.png'
export * as Background9 from './9.png'

